name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Test with Xcode
        run: |
          xcodebuild clean test \
          -project CDSample.xcodeproj \
          -scheme CDSample \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'

