name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  projectName: CDSample

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install swiftlint
        run: |
          brew install swiftlint
      - name: run swiftlint
        run: swiftlint
        continue-on-error: true
        
  build-test-lint-deploy:
    runs-on: macos-latest

    steps:
    # Checkout the repo
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Set Xcode version
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app

    # Set up Ruby (for Fastlane or bundler, if needed)
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    # Install SwiftLint
    - name: Install SwiftLint
      run: brew install swiftlint

    # Run SwiftLint
    - name: Lint Swift Code
      run: swiftlint

    # Build the Xcode project
    - name: Build Project
      run: |
        xcodebuild clean build \
        -project CDSample.xcodeproj \
        -scheme CDSample \
        -sdk iphoneos \
        -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    # Run Unit Tests
    - name: Run Unit Tests
      run: |
        xcodebuild test \
        -project CDSample.xcodeproj \
        -scheme CDSample \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0'

    # Optional: Deploy via Firebase App Distribution (example)
    - name: Deploy to Firebase
      if: github.ref == 'refs/heads/main'
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        curl -sL https://firebase.tools | bash
        firebase appdistribution:distribute build/YourApp.ipa \
          --app YOUR_FIREBASE_APP_ID \
          --groups testers \
          --token "$FIREBASE_TOKEN"
