name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  projectName: CDSample

jobs:
  build:
    runs-on: macos-14

    strategy:
      matrix: 
        destination: 
         - 'platform=iOS Simulator,name=iPhone 16,OS=18.1'

    steps:
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Checkout code
        uses: actions/checkout@v4

