name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14  # This runner supports newer Xcode versions (e.g., Xcode 15.4)

    steps:
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Test
        run: |
          xcodebuild clean test \
          -project CDSample.xcodeproj \
          -scheme CDSample \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'


