name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  projectName: CDSample

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix: 
        destination: 
         - 'platform=iOS Simulator,name=iPhone 16,OS=18.1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install swiftlint
        run: |
          brew install swiftlint


