name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  projectName: CDSample

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install swiftlint
        run: |
          brew install swiftlint
      - name: run swiftlint
        run: swiftlint
        continue-on-error: true
        
  build-test-lint-deploy:
    runs-on: macos-latest

    steps:
    # Checkout the repo
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Set Xcode version
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_16.3.app

    # Set up Ruby (for Fastlane or bundler, if needed)
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    # Install SwiftLint
    - name: Install SwiftLint
      run: brew install swiftlint

    # Run SwiftLint
    - name: Lint Swift Code
      run: swiftlint

    # Build the Xcode project
    - name: Build Project
      run: |
        xcodebuild clean build \
        -project CDSample.xcodeproj \
        -scheme CDSample \
        -sdk iphoneos \
        -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    # Run Unit Tests
    - name: Run Unit Tests
      run: |
        xcodebuild test \
        -project CDSample.xcodeproj \
        -scheme CDSample \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0'

    # Optional: Deploy via Firebase App Distribution (example)
    - name: Deploy to Firebase
      if: github.ref == 'refs/heads/main'
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        curl -sL https://firebase.tools | bash
        firebase appdistribution:distribute build/YourApp.ipa \
          --app YOUR_FIREBASE_APP_ID \
          --groups testers \
          --token "$FIREBASE_TOKEN"

          
  build-and-test:
    # The type of runner that the job will run on.
    # macOS runners are necessary for Xcode projects.
    runs-on: macos-latest

    # Environment variables for the job.
    # Replace 'YourApp' with the actual name of your Xcode project and scheme.
    env:
      XCODE_PROJECT: CDSample.xcodeproj # e.g., MySwiftUIApp.xcodeproj
      XCODE_SCHEME: CDSample             # e.g., MySwiftUIApp
      # Specify the target simulator or device for testing.
      # You can find available simulators using `xcrun simctl list devices`.
      IOS_SIMULATOR: iPhone 15 Pro Max

    # Sequence of steps that will be executed as part of this job.
    steps:
      - name: Checkout Code
        # Uses the official action to checkout your repository code.
        uses: actions/checkout@v4

      - name: Select Xcode Version
        uses: developer-tools/setup-xcode@v1
        with:
          xcode-version: 'latest'
        # Recommended action to select a specific Xcode version if needed.
        # Otherwise, the default Xcode version on macos-latest will be used.
        # You can specify a version like '15.0.1' or 'latest'.
        # uses: swift-actions/setup-xcode@v1
        # with:
        # xcode-version: 'latest'

      - name: Install Swift Package Dependencies (if any)
        # If your project uses Swift Package Manager (SPM) dependencies,
        # this step will resolve and download them.
        # For SPM, `xcodebuild -resolvePackageDependencies` is often sufficient,
        # but a clean build will also resolve them. This is mostly illustrative.
        run: |
          echo "Checking for and resolving Swift Package Manager dependencies..."
          # This command will clean and then build, which typically resolves packages.
          # We're just adding a log here to indicate the step.
          # xcodebuild -resolvePackageDependencies -project $XCODE_PROJECT -scheme $XCODE_SCHEME

      - name: Build Project
        # Builds the Xcode project for a generic iOS device.
        # This checks if the code compiles successfully.
        run: |
          echo "Building the project..."
          xcodebuild build \
            -project "$CDSample" \
            -scheme "$CDSample" \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            | xcpretty # Optional: for better formatting of xcodebuild output

      - name: Run Tests
        # Runs all unit and UI tests defined in your project.
        # Replace 'YourAppTests' if your test scheme is different.
        run: |
          echo "Running tests..."
          xcodebuild test \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -destination "platform=iOS Simulator,name=$IOS_SIMULATOR" \
            | xcpretty # Optional: for better formatting of xcodebuild output
